# Generated by Django 5.0.7 on 2024-07-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['departure_time', 'arrival_time'], name='station_jou_departu_cd8172_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['source', 'destination'], name='station_rou_source__5e1120_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('journey', 'seat'), name='unique_ticket_seat_journey'),
        ),
    ]
