# Generated by Django 5.0.7 on 2024-07-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0004_alter_ticket_order'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_ticket_seat_journey',
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('cargo', 'seat', 'journey'), name='unique_ticket'),
        ),
    ]
