# Generated by Django 5.0.7 on 2024-07-26 14:55

import station.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0006_alter_ticket_options_alter_station_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='image',
            field=models.ImageField(blank=True, upload_to=station.models.train_image_path),
        ),
    ]
